language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install node-sass --save
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  cleanup: false
  github_token: $github_token
  local_dir: ./build/
  on:
    branch: master